#! /bin/bash

mkdir $HOME/.TheChat
cd $HOME/.TheChat
PYTHON='python3'
DEST_NAME="app"

python_version=$(python3 -V 2>&1 | cut -d ' ' -f 2)
echo "python is $python_version"
if [ "$(python -V | cut -d ' ' -f 2 | cut -d '.' -f 2)" -gt 6 ]; then
  echo "Python is compatable"
else
  echo "Downloading python"
  wget -O python3.11 https://github.com/niess/python-appimage/releases/download/python3.11/python3.11.1-cp311-cp311-manylinux_2_24_x86_64.AppImage
  chmod +x python3.11
  PYTHON="$(pwd)/python3.11"
fi
git clone --branch main https://github.com/ZorionTen/TheChat.git $DEST_NAME
cd $DEST_NAME
echo "in $DEST_NAME, $PWD"
rm -r server
cd client  
echo "Creating venv"
$PYTHON -m pip install virtualenv
$PYTHON -m venv .env
source .env/bin/activate
echo 'Installing deps'
pwd
pip install --upgrade pip
pip install -r ./req.txt
echo "Starting client"
python client.py