#!/bin/bash
# Step 1: Download 'client' from the specified URL and save it to ~/.TheChat
OUTPUT_DIR="$HOME/.TheChat"
OUTPUT_FILE="$OUTPUT_DIR/client"
APPS='/usr/share/applications'
rm -r $OUTPUT_DIR
mkdir -p "$OUTPUT_DIR"
cd "$OUTPUT_DIR"
echo 'Downloading required files...'
git clone -b main https://github.com/ZorionTen/TheChat.git src
cd src/client
echo "need to install python3.8 and dev"
sudo apt install python3.8 python3.8-dev python3-venv
python3.8 -m venv .env
source .env/bin/activate
pip install --upgrade pip
pip install -r req.txt
# pyinstaller --onefile ./client.py --add-data 'views:views'
echo 'Installing...'
cat <<EOL > "$OUTPUT_FILE"
cd $OUTPUT_DIR/src/client
source .env/bin/activate
python client.py
EOL
chmod +x "$OUTPUT_FILE"
# Step 2: Create a desktop entry file for autostart
DESKTOP_FILE="$HOME/.config/autostart/thechat.desktop"
cat <<EOL > "$DESKTOP_FILE"
[Desktop Entry]
Type=Application
Exec=$OUTPUT_FILE
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name=The Chat
Comment=Your description here
EOL
echo "Adding to apps"
sudo cp $DESKTOP_FILE $APPS
# Step 3: Check the service status
echo "Chat app autostart setup complete"














